CREATE TABLE IF NOT EXISTS SUCURSAL (
CODI NUMERIC(6) NOT NULL,
ADREÇA VARCHAR(45),
TELEFON VARCHAR (9),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODI));
CREATE TABLE IF NOT EXISTS PERSONA (
DNI NUMERIC(9) NOT NULL,
NOM VARCHAR(20) NOT NULL,
COGNOM1 VARCHAR(20) NOT NULL,
COGNOM2 VARCHAR(20) NOT NULL,
ADREÇA VARCHAR(45),
TELEFON VARCHAR (9),
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI));


CREATE TABLE IF NOT EXISTS EMPLEAT (
DNI_EMP NUMERIC(9) NOT NULL,
DATA_ALTA DATE NOT NULL,
CODI_SUCURSAL NUMERIC(6),
CONSTRAINT PK_EMPLEAT PRIMARY KEY (DNI_EMP),
CONSTRAINT FK_EMP_PER_DNI FOREIGN KEY (DNI_EMP) REFERENCES PERSONA(DNI),
CONSTRAINT FK_EMP_SUC FOREIGN KEY (CODI_SUCURSAL) REFERENCES SUCURSAL(CODI));


CREATE TABLE IF NOT EXISTS PERIODISTA (
DNI_PER NUMERIC(9) NOT NULL,
ESPECIALITAT VARCHAR(20) NOT NULL,
CONSTRAINT PK_PERIODISTA PRIMARY KEY (DNI_PER),
CONSTRAINT FK_PERI_PER_DNI FOREIGN KEY (DNI_PER) REFERENCES PERSONA(DNI));
CREATE TABLE IF NOT EXISTS REVISTA (
NUM_REGISTRE NUMERIC(6) NOT NULL,
NOM VARCHAR(20),
PERIODICITAT VARCHAR (9),
TIPUS VARCHAR(20),
CODI_SUCURSAL NUMERIC(6),
CONSTRAINT CK_PERIODICITAT CHECK (PERIODICITAT IN ('Diaria','Setmanal','Mensual')),
CONSTRAINT PK_REVISTA PRIMARY KEY (NUM_REGISTRE),
CONSTRAINT FK_REV_SUC FOREIGN KEY (CODI_SUCURSAL) REFERENCES SUCURSAL(CODI));


CREATE TABLE IF NOT EXISTS COLABORA (
NUM_REGISTRE_COL NUMERIC(6) NOT NULL,
DNI_PER_COL NUMERIC(9) NOT NULL,
CONSTRAINT PK_COLABORA PRIMARY KEY (NUM_REGISTRE_COL,DNI_PER_COL),
CONSTRAINT FK_COL_REV FOREIGN KEY (NUM_REGISTRE_COL) REFERENCES REVISTA(NUM_REGISTRE),
CONSTRAINT FK_COL_PER FOREIGN KEY (DNI_PER_COL) REFERENCES PERIODISTA(DNI_PER));