CREATE TABLE MY_EMPLOYEE
(ID NUMERIC (4),
LAST_NAME VARCHAR(25),
FIRST_NAME VARCHAR(25),
USERID VARCHAR(8),
SALARY DOUBLE PRECISION DEFAULT 10000,
CONSTRAINT PK_MY_EMPLOYEE PRIMARY KEY (ID)
);


INSERT INTO MY_EMPLOYEE VALUES (1, 'Patel', 'Ralph', 'rpatel', '895');
INSERT INTO MY_EMPLOYEE VALUES (2, 'Dancs', 'Betty', 'bdancs', '860');
INSERT INTO MY_EMPLOYEE VALUES (3, 'Biri', 'Ben', NULL, '1100');
INSERT INTO MY_EMPLOYEE VALUES (4, 'Newman', 'Chad', NULL, '750');
INSERT INTO MY_EMPLOYEE VALUES (5, 'Ropeburn', 'Audrey', 'aropebur', '1550');


SELECT * FROM MY_EMPLOYEE;

INSERT INTO MY_EMPLOYEE VALUES (6, 'Enric', 'Struch', 'estruch', DEFAULT);
SELECT * FROM MY_EMPLOYEE;


INSERT INTO MY_EMPLOYEE (ID,LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (1, 'Patel',
'Ralph', 'rpatel', 895);
INSERT INTO MY_EMPLOYEE (ID,LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (2, 'Dancs',
'Betty', 'bdancs', 860);
INSERT INTO MY_EMPLOYEE (ID,LAST_NAME, FIRST_NAME, SALARY)
VALUES (3, 'Biri', 'Ben', 1500);
INSERT INTO MY_EMPLOYEE (SALARY,ID,LAST_NAME, FIRST_NAME)
VALUES (750,4, 'Newman', 'Chad');
INSERT INTO MY_EMPLOYEE (ID,LAST_NAME, FIRST_NAME, USERID,SALARY)
VALUES (5, 'Ropeburn', 'Audrey', 'aropebur', 1550);
INSERT INTO MY_EMPLOYEE (ID,LAST_NAME, FIRST_NAME, USERID)
VALUES (6, 'Enric', 'Struch', 'estruch');


UPDATE MY_EMPLOYEE SET USERID='bben' WHERE ID= 3;
UPDATE MY_EMPLOYEE SET USERID='nchad' WHERE ID= 4;
SELECT * FROM MY_EMPLOYEE;


UPDATE MY_EMPLOYEE SET LAST_NAME= 'Drexler' WHERE ID= 3;
SELECT * FROM MY_EMPLOYEE;

UPDATE MY_EMPLOYEE SET SALARY= 1000 WHERE SALARY < 900;
SELECT * FROM MY_EMPLOYEE;


DELETE FROM MY_EMPLOYEE WHERE FIRST_NAME= 'Betty';
SELECT * FROM MY_EMPLOYEE;


DELETE FROM MY_EMPLOYEE WHERE ID = 5;


TRUNCATE TABLE MY_EMPLOYEE;
SELECT * FROM MY_EMPLOYEE