-- Crea un base de dades anomenada empleats
CREATE DATABASE empleats;
-- Crea un usuari anomenat empleats amb la contrasenya 'empleats' i perfil de superusuari
CREATE USER empleats WITH SUPERUSER CREATEROLE ENCRYPTED PASSWORD 'empleats';
-- Assigna l'usuari empleats com a propietari de la BBDD empleats
ALTER DATABASE empleats OWNER TO empleats;
-- Assigna tots els privilegis a l'usuari empleats sobre la BBDD empleats
GRANT ALL PRIVILEGES ON DATABASE empleats TO empleats;

--Creem les taules
CREATE TABLE REGION
(
CODREGION NUMERIC(5) NOT NULL,
NOMBRE VARCHAR(40),
CONSTRAINT PK_REGION PRIMARY KEY (CODREGION));

CREATE TABLE PROVINCIA
(
CODPROVINCIA NUMERIC(5) NOT NULL,
NOMBRE VARCHAR(40),
CODREGION NUMERIC(5), 
CONSTRAINT PK_PROVINCIA PRIMARY KEY (CODPROVINCIA),
CONSTRAINT FK_PROV_REG_CODREGION FOREIGN KEY (CODREGION) REFERENCES REGION(CODREGION));


CREATE TABLE LOCALIDAD
(
CODLOCALIDAD NUMERIC(5) NOT NULL,
NOMBRE VARCHAR(40),
CODPROVINCIA NUMERIC(5), 
CONSTRAINT PK_LOCALIDAD PRIMARY KEY (CODLOCALIDAD),
CONSTRAINT FK_LOC_PROV_CODPROVINCIA FOREIGN KEY (CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA));

CREATE TABLE EMPLEADO
(
ID NUMERIC(3) NOT NULL,
DNI CHAR(9) UNIQUE,
NOMBRE VARCHAR(50),
FECHANAC DATE,
TELEFONO CHAR(9),
SALARIO NUMERIC(6,2),
CODLOCALIDAD NUMERIC(5),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID),
CONSTRAINT FK_EMP_LOC_CODLOCALIDAD_ FOREIGN KEY (CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD));
