CREATE TABLE IF NOT EXISTS LOCALITAT (
COD_LOCALITAT NUMERIC (10) CONSTRAINT PK_LOCALITAT PRIMARY KEY,
NOM VARCHAR (10) NOT NULL);


CREATE TABLE IF NOT EXISTS PUB (
COD_PUB VARCHAR (10) CONSTRAINT PK_PUB PRIMARY KEY,
NOM VARCHAR (20)NOT NULL,
LLICENCIA VARCHAR (20)NOT NULL,
DOMILICI VARCHAR (20) NULL,
DATA_APERTURA DATE NOT NULL,
HORARI VARCHAR (20)NOT NULL,
COD_LOCALITAT NUMERIC (10) NOT NULL,
CONSTRAINT CK_HORARI CHECK (HORARI IN ('HOR1', 'HOR2', 'HOR3')),
CONSTRAINT FK_PUB_LOC FOREIGN KEY (COD_LOCALITAT) REFERENCES LOCALITAT (COD_LOCALITAT));


CREATE INDEX IDX_PUB_COD_LOCALITAT on PUB (COD_LOCALITAT);
CREATE TABLE IF NOT EXISTS TITULAR (
DNI_TITULAR VARCHAR (10) CONSTRAINT PK_TITULAR PRIMARY KEY,
NOM VARCHAR (20)NOT NULL,
DOMICILI VARCHAR (20),
COD_PUB VARCHAR (10) NOT NULL,
CONSTRAINT FK_TIT_PUB FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB));


CREATE INDEX IDX_TITULAR_COD_PUB on TITULAR (COD_PUB);


CREATE TABLE IF NOT EXISTS EMPLEAT (
DNI_EMPLEAT VARCHAR (10) CONSTRAINT PK_EMPLEAT PRIMARY KEY,
NOM VARCHAR (20) NOT NULL,
DOMICILI VARCHAR (20));
CREATE TABLE IF NOT EXISTS ARTICLE (
COD_ARTICLE VARCHAR (4) CONSTRAINT PK_ARTICLE PRIMARY KEY,
NOM VARCHAR (20)NOT NULL,
QUANTITAT NUMERIC (8)NOT NULL,
PREU NUMERIC (4) NOT NULL,
COD_PUB VARCHAR (10) NOT NULL,
CONSTRAINT CK_PREU CHECK (PREU >0),
CONSTRAINT FK_ART_PUB FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB));


CREATE TABLE IF NOT EXISTS PUB_EMPLEAT (
COD_PUB VARCHAR (10) NOT NULL,
DNI_EMPLEAT VARCHAR (10) NOT NULL,
FUNCIO VARCHAR (20) NOT NULL,
CONSTRAINT CK_FUNCIO CHECK (FUNCIO IN ('Cambrer', 'Seguretat', 'Neteja')),
CONSTRAINT PUB_EMPLEAT_PK PRIMARY KEY (COD_PUB,DNI_EMPLEAT),
CONSTRAINT FK_PUBEMP_PUB FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB),
CONSTRAINT FK_PUBEMP_EMP FOREIGN KEY (DNI_EMPLEAT) REFERENCES EMPLEAT (DNI_EMPLEAT));


CREATE INDEX IDX_PUB_COD_PUB on PUB_EMPLEAT (COD_PUB);